<input id="raceID" placeholder="enter race id"></input>
<button id="confirm">confirm</button>
<!-- show this screen first then the rest -->

<p id="stopwatch">00 : 00 :00 : 00</p>

<button id="timerBttn">start</button>
<button id="recordBttn">record</button>

<ol id="runners">
</ol>

<button id="uploadBttn">upload</button>
<p id="uploadMssg">Race Uploaded!</p>

<button id="viewResults">view results</button>